name: leetcode

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: CMake
      run: |
        sudo apt update
        sudo apt install cmake clang ninja-build -y
        mkdir build
        cd build
        cmake ../ -G Ninja
        ninja -j12
        ctest
    - name: Run codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
    - name: sending msg
      uses: yakumioto/serverchan-action@v1
      with:
        key: SCU78225T45c3728a9ecec4b87130557beb6136135e24105f2edfc
        text: "leetcode单元测试通过"
        desp: "leetcode单元测试通过"
